version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: FuriousKopan
      POSTGRES_PASSWORD: packaras
      POSTGRES_DB: top10media
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=top10media;Username=FuriousKopan;Password=packaras"
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
